- name: Check if netdata is already installed
  become: yes
  stat:
    path: /usr/sbin/netdata
  register: netdata_bin

- name: Install netdata from upstream kickstart if not present
  become: yes
  shell: |
    bash <(curl -Ss https://raw.githubusercontent.com/netdata/netdata/master/packaging/installer/kickstart.sh)
  args:
    warn: false
  when: not netdata_bin.stat.exists

- name: Allow Netdata listen on all interfaces
  become: yes
  ini_file:
    path: /etc/netdata/netdata.conf
    section: web
    option: 'bind to'
    value: '0.0.0.0'
    backup: yes

- name: Restart network services to ensure new service is reachable
  become: yes
  shell: |
    set -e
    systemctl restart networking || true
    systemctl restart NetworkManager || true
    netplan apply || true
  args:
    warn: false

- name: Ensure netdata service is started and enabled
  become: yes
  systemd:
    name: netdata
    state: restarted
    enabled: yes

- name: Wait for netdata HTTP port to be available on loopback
  become: yes
  wait_for:
    host: 127.0.0.1
    port: 19999
    timeout: 60
    state: started