- name: Install ufw
  apt:
    name: ufw
    state: present
    update_cache: yes

- name: Allow SSH
  ufw:
    rule: allow
    port: "22"
    proto: tcp

- name: Allow HTTP (load balancer)
  ufw:
    rule: allow
    port: "80"
    proto: tcp

- name: Allow Netdata (19999) for monitoring
  ufw:
    rule: allow
    port: "19999"
    proto: tcp

- name: Enable UFW
  ufw:
    state: enabled