- name: Base configuration for all hosts
  hosts: all
  become: yes
  roles:
    - base
    - docker
    - hardening
    - netdata

- name: Deploy backend on app server
  hosts: app
  become: yes
  roles:
    - app

- name: Deploy frontend on web server
  hosts: web
  become: yes
  roles:
    - frontend

- name: Configure load balancer
  hosts: loadbalancer
  become: yes
  roles:
    - loadbalancer

- name: Backup server tasks
  hosts: backup
  become: yes
  roles:
    - backup

- name: CI host tasks
  hosts: ci
  become: yes
  roles:
    - ci        